version: 2
workspace_root: &workspace_root
  /tmp/workspace
attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace_root

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - *attach_workspace
      - checkout
      - run: mkdir /tmp/workspace/target
      - run: go build -mod=vendor -o /tmp/workspace/target/test
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - target
  run:
    docker:
      - image: circleci/golang:1.12
    steps:
      - *attach_workspace
      - checkout
      - run: /tmp/workspace/target/test
workflows:
  version: 2
  build:
    jobs:
      - build
      - run:
          requires:
            - build
